def deliver_document(document="", content="", **kwargs):
    """Format and deliver the final academic paper."""
    # Get document from either parameter
    doc = document or content or kwargs.get("summary") or ""
    
    if not doc or len(doc.strip()) < 100:
        return {
            "status": "error",
            "final_output": "",
            "message": "No document content to deliver"
        }
    
    # Add formatting header
    header = "="*60 + "\n"
    header += "AI 최신 동향 분석 학술 논문\n"
    header += "Generated by AI Research Analyst Agent\n"
    header += "="*60 + "\n\n"
    
    footer = "\n\n" + "="*60 + "\n"
    footer += "논문 생성 완료\n"
    footer += "="*60
    
    final_output = header + doc + footer
    
    return {
        "status": "success",
        "final_output": final_output,
        "document": final_output,
        "content": final_output
    }
